# pylint: skip-file

"""Changed Community.avatar_url.

Revision ID: 03782c2878c7
Revises: 
Create Date: 2024-05-01 01:13:46.321135

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "03782c2878c7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("avatar_url", sa.String(length=300), nullable=True)
        )
        batch_op.drop_column("avatar")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(sa.Column("avatar", sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column("avatar_url")

    # ### end Alembic commands ###
