"""Changed UserLike.reply_id.

Revision ID: 0a3d1a8b7316
Revises: c9f86a7f9003
Create Date: 2024-05-02 20:13:04.731189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3d1a8b7316'
down_revision = 'c9f86a7f9003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_like', schema=None) as batch_op:
        batch_op.alter_column('request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_user_like_reply_id_reply', type_='foreignkey')
        batch_op.drop_column('reply_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_like_reply_id_reply', 'reply', ['reply_id'], ['id'])
        batch_op.alter_column('request_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
