"""Added Trending.view_num.

Revision ID: 4a42bc57510d
Revises: a3910eddd6d3
Create Date: 2024-05-06 01:57:50.818278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a42bc57510d'
down_revision = 'a3910eddd6d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
