# pylint: skip-file

"""Added UserLike Table.

Revision ID: 7f3348c5a4e6
Revises: 3e3522f2825b
Create Date: 2024-05-02 20:07:01.779781

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7f3348c5a4e6"
down_revision = "3e3522f2825b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_like",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=True),
        sa.Column("reply_id", sa.Integer(), nullable=True),
        sa.Column("create_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reply_id"], ["reply.id"], name=op.f("fk_user_like_reply_id_reply")
        ),
        sa.ForeignKeyConstraint(
            ["request_id"], ["request.id"], name=op.f("fk_user_like_request_id_request")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_user_like_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_like")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_like")
    # ### end Alembic commands ###
