# pylint: skip-file

"""Added Reply.reply_id.

Revision ID: 80b5573526cc
Revises: 3e3522f2825b
Create Date: 2024-05-02 00:01:04.528593

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "80b5573526cc"
down_revision = "3e3522f2825b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reply", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reply_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_reply_reply_id_reply"), "reply", ["reply_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reply", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_reply_reply_id_reply"), type_="foreignkey"
        )
        batch_op.drop_column("reply_id")

    # ### end Alembic commands ###
