"""Added Trending.view_num.

Revision ID: a3910eddd6d3
Revises: 25c9027f6758
Create Date: 2024-05-06 01:50:46.029526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3910eddd6d3'
down_revision = '25c9027f6758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trending', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_num', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_type', sa.Enum('REQUEST', 'REPLY', 'VIEW', 'LIKE', 'SAVE', name='userrecordtypeenum'), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('update_at')
        batch_op.drop_column('record_type')

    with op.batch_alter_table('trending', schema=None) as batch_op:
        batch_op.drop_column('view_num')

    # ### end Alembic commands ###
