# pylint: skip-file

"""Added Community.author_id.

Revision ID: ac971512e469
Revises: 19560463f70c
Create Date: 2024-05-05 16:14:38.475037

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ac971512e469"
down_revision = "19560463f70c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("creator_id", sa.String(length=36), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_community_creator_id_user"), "user", ["creator_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_community_creator_id_user"), type_="foreignkey"
        )
        batch_op.drop_column("creator_id")

    # ### end Alembic commands ###
