"""Added UserSave Table.

Revision ID: c9f86a7f9003
Revises: 7f3348c5a4e6
Create Date: 2024-05-02 20:11:39.188445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f86a7f9003'
down_revision = '7f3348c5a4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_save',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], name=op.f('fk_user_save_request_id_request')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_save_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_save'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_save')
    # ### end Alembic commands ###
