# pylint: skip-file

"""Changed Trending.request_title.

Revision ID: e2379553e5a7
Revises: f72e4837cebb
Create Date: 2024-05-01 01:47:40.041095

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e2379553e5a7"
down_revision = "f72e4837cebb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_alembic_tmp_trending")
    with op.batch_alter_table("trending", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("request_title", sa.String(length=40), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_trending_request_title_request"),
            "request",
            ["request_title"],
            ["title"],
        )
        batch_op.drop_column("title")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trending", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title", sa.VARCHAR(length=40), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("fk_trending_request_title_request"), type_="foreignkey"
        )
        batch_op.drop_column("request_title")

    op.create_table(
        "_alembic_tmp_trending",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("request_id", sa.INTEGER(), nullable=False),
        sa.Column("author_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("reply_num", sa.INTEGER(), nullable=True),
        sa.Column("date", sa.VARCHAR(length=10), nullable=True),
        sa.Column("update_at", sa.DATETIME(), nullable=True),
        sa.Column("request_title", sa.VARCHAR(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["user.id"], name="fk_trending_author_id_user"
        ),
        sa.ForeignKeyConstraint(
            ["request_id"], ["request.id"], name="fk_trending_request_id_request"
        ),
        sa.ForeignKeyConstraint(
            ["request_title"],
            ["request.title"],
            name="fk_trending_request_title_request",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_trending"),
        sa.UniqueConstraint("request_id", name="uq_trending_request_id"),
    )
    # ### end Alembic commands ###
