# pylint: skip-file

"""Changed Notice.module.

Revision ID: f72e4837cebb
Revises: 03782c2878c7
Create Date: 2024-05-01 01:24:15.489107

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f72e4837cebb"
down_revision = "03782c2878c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notice", schema=None) as batch_op:
        batch_op.add_column(sa.Column("module", sa.String(length=50), nullable=True))
        batch_op.drop_column("notice_type")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notice", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("notice_type", sa.VARCHAR(length=50), nullable=True)
        )
        batch_op.drop_column("module")

    # ### end Alembic commands ###
