"""Category model."""

import datetime

from app.extensions import db
from app.utils import format_datetime_to_readable_string, generate_time


class Category(db.Model):
    """Category model."""

    id: int = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name: str = db.Column(db.String(20), unique=True, nullable=False)
    create_at: datetime = db.Column(db.DateTime, default=generate_time())

    def __init__(self, name: str) -> None:
        self.name = name

    def __repr__(self) -> str:
        """Return a string representation of the category."""

        return f"<Category {self.name}>"

    # generated by copilot
    def to_dict(self) -> dict:
        """Return a JSON format of the category."""

        return {
            "id": self.id,
            "name": self.name,
            "create_at": format_datetime_to_readable_string(self.create_at),
        }
