"""Community model."""

import datetime

from sqlalchemy import event

from app.constants import DICEBEAR_AVATAR_URL
from app.extensions import db
from app.utils import format_datetime_to_readable_string, generate_time


# pylint: disable=too-many-arguments
class Community(db.Model):
    """Community model."""

    id: int = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name: str = db.Column(db.String(20), unique=True, nullable=False)
    category_id: int = db.Column(db.Integer, db.ForeignKey("category.id"))
    description: str = db.Column(db.String(500))
    avatar_url: str = db.Column(db.String(300))
    creator_id: str = db.Column(db.String(36), db.ForeignKey("user.id"))
    create_at: datetime = db.Column(db.DateTime, default=generate_time())
    update_at: datetime = db.Column(
        db.DateTime, default=generate_time(), onupdate=generate_time()
    )

    category = db.relationship("Category", backref=db.backref("communities", lazy=True))
    creator = db.relationship("User", backref=db.backref("communities", lazy=True))

    def __init__(
        self,
        name: str,
        category_id: int,
        description: str = "",
        avatar_url: str = "",
        creator_id: str = "",
    ) -> None:
        self.name = name
        self.category_id = category_id
        self.description = description
        self.avatar_url = avatar_url
        self.creator_id = creator_id

    def __repr__(self) -> str:
        """Return a string representation of the community."""

        return f"<Community {self.name}>"

    # generated by copilot
    def to_dict(self) -> dict:
        """Return a JSON format of the community."""

        return {
            "id": self.id,
            "name": self.name,
            "category": self.category.to_dict() if self.category else None,
            "description": self.description,
            "avatar_url": self.avatar_url,
            "creator": self.creator.to_dict() if self.creator else None,
            "create_at": format_datetime_to_readable_string(self.create_at),
            "update_at": format_datetime_to_readable_string(self.update_at),
        }


@event.listens_for(Community, "before_insert")
def before_insert_listener(_, __, target) -> None:
    """Update the create time before inserting a new user."""

    target.avatar_url = check_avatar_url(target.avatar_url, target.name)


def check_avatar_url(avatar_url: str, name: str) -> None:
    """Check the avatar url."""

    if not avatar_url:
        formatted_name = name.replace(" ", "_")
        return f"{DICEBEAR_AVATAR_URL}{formatted_name}"

    return avatar_url
