"""Request model."""

import datetime

from app.extensions import db
from app.utils import format_datetime_to_readable_string, generate_time


# pylint: disable=too-many-instance-attributes
class Request(db.Model):
    """Request model."""

    id: int = db.Column(db.Integer, primary_key=True, autoincrement=True)
    author_id: str = db.Column(db.String(36), db.ForeignKey("user.id"), nullable=False)
    title: str = db.Column(db.String(40), nullable=False)
    content: str = db.Column(db.String(1000), default="")
    community_id: int = db.Column(
        db.Integer, db.ForeignKey("community.id"), nullable=False
    )
    tag_id: int = db.Column(db.Integer, db.ForeignKey("tag.id"))
    view_num: int = db.Column(db.Integer)
    like_num: int = db.Column(db.Integer)
    reply_num: int = db.Column(db.Integer)
    save_num: int = db.Column(db.Integer)
    create_at: datetime = db.Column(db.DateTime, default=generate_time())
    update_at: datetime = db.Column(
        db.DateTime, default=generate_time(), onupdate=generate_time()
    )

    author = db.relationship("User", backref=db.backref("requests", lazy=True))
    community = db.relationship("Community", backref=db.backref("requests", lazy=True))
    tag = db.relationship("Tag", backref=db.backref("requests", lazy=True))

    # pylint: disable=too-many-arguments
    def __init__(
        self,
        author_id: str,
        title: str,
        content: str,
        community_id: int,
        tag_id: int,
        view_num: int,
        like_num: int,
        reply_num: int,
        save_num: int,
    ) -> None:
        self.author_id = author_id
        self.title = title
        self.content = content
        self.community_id = community_id
        self.tag_id = tag_id
        self.view_num = view_num
        self.like_num = like_num
        self.reply_num = reply_num
        self.save_num = save_num

    def __repr__(self) -> str:
        """Return a string representation of the request."""

        return f"<Request {self.id}>"

    # generated by copilot
    def to_dict(self):
        """Return a JSON format of the request."""

        return {
            "id": self.id,
            "author": self.author.to_dict() if self.author else None,
            "title": self.title,
            "content": self.content,
            "community": self.community.to_dict() if self.community else None,
            "tag": self.tag.to_dict() if self.tag else None,
            "view_num": self.view_num,
            "like_num": self.like_num,
            "reply_num": self.reply_num,
            "save_num": self.save_num,
            "create_at": format_datetime_to_readable_string(self.create_at),
            "update_at": format_datetime_to_readable_string(self.update_at),
        }
